/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gp2.clinica_estetica.view;

import com.gp2.clinica_estetica.controller.AttendanceController;
import com.gp2.clinica_estetica.model.Attendance;
import com.gp2.clinica_estetica.view.util.WeekCalendar;
import com.gp2.clinica_estetica.model.User;
import com.mindfusion.common.DateTime;
import java.util.Calendar;
import java.util.List;
import java.util.TimeZone;
import javax.swing.JFrame;

/**
 *
 * @author darloonlino
 */
public class FrAttendantHome extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form FrAttendant
     */
    public FrAttendantHome() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        btnExit.setOpaque(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setBorderPainted(false);

        this.setWeekCalendar();
    }

    /**
     * Creates new form FrAttendant
     */
    public FrAttendantHome(User currentUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.user = currentUser;

        btnExit.setOpaque(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setBorderPainted(false);

        this.setWeekCalendar();
    }

    public void setWeekCalendar() {
        AttendanceController attendanceCon = new AttendanceController();
        List<Attendance> attendances = attendanceCon.onFindAll();
        WeekCalendar calendar = new WeekCalendar(boxCalendar.getSize(), this);
        
        for(int i = 0; i < attendances.size(); i++) {
            Attendance currentAttendance = attendances.get(i);
            
            currentAttendance.getStartDateTime().setTimeZone(TimeZone.getDefault());
            DateTime dt = new DateTime(
                    currentAttendance.getStartDateTime().get(Calendar.YEAR),
                    currentAttendance.getStartDateTime().get(Calendar.MONTH) + 1,
                    currentAttendance.getStartDateTime().get(Calendar.DAY_OF_MONTH),
                    currentAttendance.getStartDateTime().get(Calendar.HOUR_OF_DAY),
                    currentAttendance.getStartDateTime().get(Calendar.MINUTE),
                    00);
            
            currentAttendance.getEndDateTime().setTimeZone(TimeZone.getDefault());
            DateTime dt2 = new DateTime(
                    currentAttendance.getEndDateTime().get(Calendar.YEAR),
                    currentAttendance.getEndDateTime().get(Calendar.MONTH) + 1,
                    currentAttendance.getEndDateTime().get(Calendar.DAY_OF_MONTH),
                    currentAttendance.getEndDateTime().get(Calendar.HOUR_OF_DAY),
                    currentAttendance.getEndDateTime().get(Calendar.MINUTE),
                    00);

            calendar.addItem(
                    currentAttendance.getProcedure().getName(), 
                    currentAttendance.getPatient().getPeople().getName(),
                    dt,
                    dt2,
                    "" + currentAttendance.getId());         
        }
        boxCalendar.add(calendar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnPatientsList = new javax.swing.JButton();
        btnAddCalendarPoint = new javax.swing.JButton();
        boxCalendar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Atendente");

        btnExit.setForeground(new java.awt.Color(25, 25, 25));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnPatientsList.setText("Pacientes");
        btnPatientsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsListActionPerformed(evt);
            }
        });

        btnAddCalendarPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus.png"))); // NOI18N
        btnAddCalendarPoint.setBorder(null);
        btnAddCalendarPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCalendarPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCalendarPointActionPerformed(evt);
            }
        });

        boxCalendar.setPreferredSize(new java.awt.Dimension(0, 400));

        javax.swing.GroupLayout boxCalendarLayout = new javax.swing.GroupLayout(boxCalendar);
        boxCalendar.setLayout(boxCalendarLayout);
        boxCalendarLayout.setHorizontalGroup(
            boxCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        boxCalendarLayout.setVerticalGroup(
            boxCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnPatientsList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCalendarPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPatientsList)
                    .addComponent(btnAddCalendarPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boxCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        FrLogin loginScreen = new FrLogin();
        loginScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPatientsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsListActionPerformed
        // TODO add your handling code here:
        FrPatientsList patientsListScreen = new FrPatientsList(user);
        patientsListScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPatientsListActionPerformed

    private void btnAddCalendarPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCalendarPointActionPerformed
        // TODO add your handling code here:
        FrAttendance attendanceScreen = new FrAttendance("create");
        attendanceScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddCalendarPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAttendantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAttendantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAttendantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAttendantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrAttendantHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCalendar;
    private javax.swing.JButton btnAddCalendarPoint;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPatientsList;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
