/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gp2.clinica_estetica.view;

import com.gp2.clinica_estetica.controller.ContractController;
import com.gp2.clinica_estetica.model.Contract;
import com.gp2.clinica_estetica.model.People;
import com.gp2.clinica_estetica.model.exceptions.ContractException;
import com.gp2.clinica_estetica.model.exceptions.ReportsException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author darloonlino
 */
public class FrContract extends javax.swing.JFrame {

    private String type; // "Patient" | "Attendant"
    private ContractController contractCon;
    private People people;
    private JFrame previusScreen;

    /**
     * Creates new form FrContratos
     */
    public FrContract() {
        initialize();
    }

    /**
     * Creates new form FrContratos
     *
     * @param previusScreen
     * @param people
     */
    public FrContract(JFrame previusScreen, People people) {
        this.previusScreen = previusScreen;
        this.people = people;

        initialize();
        if (people.getPatient() != null) {
            type = "Patient";
            // load 

            contractCon.updateTableWithUnsigned(table, this.people.getCPF(), "");
        }
        if (people.getAttendant() != null) {
            type = "Attendant";
            contractCon.updateTableWithUnsigned(table, "");
            boxContractFilter.setVisible(false);
            btnPrintAll.setVisible(false);
        }
    }

    public void initialize() {
        initComponents();

        contractCon = new ContractController();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        btnPrintAll.setOpaque(false);
        btnPrintAll.setContentAreaFilled(false);
        btnPrintAll.setBorderPainted(false);

        grupoEstadoContrato.setSelected(radioNovos.getModel(), true);

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstadoContrato = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnPrintAll = new javax.swing.JButton();
        boxContractFilter = new javax.swing.JPanel();
        radioNovos = new javax.swing.JRadioButton();
        radioAssindos = new javax.swing.JRadioButton();
        radioExpirdos = new javax.swing.JRadioButton();
        boxFilterByProcedure = new javax.swing.JPanel();
        fieldSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        title.setText("Contratos");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20/04/2022", "Limpeza de Pele", null, "R$ 69,90"},
                {"06/04/2022", "Sombracelha", null, "R$ 45,00"}
            },
            new String [] {
                "Data", "Procedimento", "Paciente", "Valor"
            }
        ));
        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnPrintAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        btnPrintAll.setBorder(null);
        btnPrintAll.setBorderPainted(false);
        btnPrintAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllActionPerformed(evt);
            }
        });

        grupoEstadoContrato.add(radioNovos);
        radioNovos.setText("Novos");
        radioNovos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNovosActionPerformed(evt);
            }
        });

        grupoEstadoContrato.add(radioAssindos);
        radioAssindos.setText("Assinados");
        radioAssindos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAssindosActionPerformed(evt);
            }
        });

        grupoEstadoContrato.add(radioExpirdos);
        radioExpirdos.setText("Expirdos");
        radioExpirdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExpirdosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxContractFilterLayout = new javax.swing.GroupLayout(boxContractFilter);
        boxContractFilter.setLayout(boxContractFilterLayout);
        boxContractFilterLayout.setHorizontalGroup(
            boxContractFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxContractFilterLayout.createSequentialGroup()
                .addComponent(radioNovos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioAssindos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioExpirdos)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        boxContractFilterLayout.setVerticalGroup(
            boxContractFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxContractFilterLayout.createSequentialGroup()
                .addGroup(boxContractFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAssindos)
                    .addComponent(radioNovos)
                    .addComponent(radioExpirdos))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Pesquise pelo nome do procedimento");

        javax.swing.GroupLayout boxFilterByProcedureLayout = new javax.swing.GroupLayout(boxFilterByProcedure);
        boxFilterByProcedure.setLayout(boxFilterByProcedureLayout);
        boxFilterByProcedureLayout.setHorizontalGroup(
            boxFilterByProcedureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxFilterByProcedureLayout.createSequentialGroup()
                .addGroup(boxFilterByProcedureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxFilterByProcedureLayout.createSequentialGroup()
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        boxFilterByProcedureLayout.setVerticalGroup(
            boxFilterByProcedureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxFilterByProcedureLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boxFilterByProcedureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        btnBack2.setText("Voltar");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxContractFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxFilterByProcedure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrintAll)
                    .addComponent(title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(boxContractFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxFilterByProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAssindosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAssindosActionPerformed
        // TODO add your handling code here:
        contractCon.updateTableWithSigned(table, this.people.getCPF(), fieldSearch.getText());
        if (table.getRowCount() < 1) {
            btnPrintAll.setEnabled(false);
        } else {
            btnPrintAll.setEnabled(true);
        }
    }//GEN-LAST:event_radioAssindosActionPerformed

    private void radioNovosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNovosActionPerformed
        // TODO add your handling code here:
        contractCon.updateTableWithUnsigned(table, this.people.getCPF(), fieldSearch.getText());
        if (table.getRowCount() < 1) {
            btnPrintAll.setEnabled(false);
        } else {
            btnPrintAll.setEnabled(true);
        }
    }//GEN-LAST:event_radioNovosActionPerformed

    private void radioExpirdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExpirdosActionPerformed
        // TODO add your handling code here:
        contractCon.updateTableWithExpired(table, this.people.getCPF(), fieldSearch.getText());
        if (table.getRowCount() < 1) {
            btnPrintAll.setEnabled(false);
        } else {
            btnPrintAll.setEnabled(true);
        }
    }//GEN-LAST:event_radioExpirdosActionPerformed

    private void tablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePropertyChange

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) {
            int row = table.getSelectedRow();
            Contract contractRow = (Contract) table.getValueAt(row, -1);

            if (this.type.equals("Attendant")) {

                int response = JOptionPane.showConfirmDialog(null,
                        "Marcar esse contrato como assinado?",
                        contractRow.getProcedure().getName() + " - " + contractRow.getPatient().getPeople().getName(),
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        contractCon.onSetAsSigned(contractRow.getId());
                        contractCon.updateTableWithUnsigned(table, "");
                    } catch (ContractException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
            } else {
                if (contractRow.getFile() == null) {
                    JOptionPane.showMessageDialog(this, "Contrato indisponível");
                    return;
                }
                int response = JOptionPane.showConfirmDialog(null,
                        "Baixar esse contrato?",
                        "Contrato de " + contractRow.getProcedure().getName(),
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);

                if (response == JOptionPane.YES_OPTION) {
                    String nameFile = contractRow.getFile();
                    File src = new File("src/main/resources/contracts/" + nameFile);
                    File dest = new File(nameFile);
                    try {
                        contractRow.saveFile(src, dest);
                        JOptionPane.showMessageDialog(this, "Contrato gerado com sucesso!");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Erro ao salvar contrato " + nameFile);
                    }
                }
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllActionPerformed
        // TODO add your handling code here:
        if (table.getRowCount() < 1) {
            return;
        }

        int response = JOptionPane.showConfirmDialog(null,
                "Baixar o relatório dessa listagem de contratos?",
                "Relatório de listagem completa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                Contract contract = new Contract();

                contract.generateTablePDF("Lista_de_contratos.pdf", "Lista de contratos", table);
                JOptionPane.showMessageDialog(this, "Listagem de contratos gerada com sucesso!");
            } catch (ReportsException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnPrintAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.type.equals("Attendant")) {
            contractCon.updateTableWithUnsigned(table, fieldSearch.getText());
            fieldSearch.setText("");
            return;
        }
        if (radioNovos.isSelected()) {
            contractCon.updateTableWithUnsigned(table, this.people.getCPF(), fieldSearch.getText());
        }
        if (radioAssindos.isSelected()) {
            contractCon.updateTableWithSigned(table, this.people.getCPF(), fieldSearch.getText());
        }
        if (radioExpirdos.isSelected()) {
            contractCon.updateTableWithExpired(table, this.people.getCPF(), fieldSearch.getText());
        }

        if (table.getRowCount() < 1) {
            btnPrintAll.setEnabled(false);
        } else {
            btnPrintAll.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        previusScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxContractFilter;
    private javax.swing.JPanel boxFilterByProcedure;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnPrintAll;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.ButtonGroup grupoEstadoContrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioAssindos;
    private javax.swing.JRadioButton radioExpirdos;
    private javax.swing.JRadioButton radioNovos;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
