/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gp2.clinica_estetica.view;

import com.gp2.clinica_estetica.controller.AttendanceController;
import com.gp2.clinica_estetica.controller.ProcedureController;
import com.gp2.clinica_estetica.model.Attendance;
import com.gp2.clinica_estetica.model.MedicalProcedure;
import com.gp2.clinica_estetica.model.User;
import com.gp2.clinica_estetica.model.exceptions.ReportsException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author nuria
 */
public class FrReport extends javax.swing.JFrame {

    JFrame previusScreen;
    AttendanceController attendanceCon;
    private java.util.List<MedicalProcedure> procedures;
    User user;

    /**
     * Creates new form FrRelatorio
     */
    public FrReport() {
        initialize();
    }

    /**
     * Creates new form FrRelatorio
     *
     * @param previusScreen
     * @param user
     */
    public FrReport(JFrame previusScreen, User user) {
        initialize();
        this.previusScreen = previusScreen;
        this.user = user;

        title.setText("Relatórios - " + user.getPeople().getName());
        attendanceCon = new AttendanceController();
        attendanceCon.onFindAllFilter(table, user.getPeople().getCPF(), "Avaliacao", null, "", 0.0);
        fieldPrice.setEnabled(false);
        fieldPrice.setText("R$ ");
    }

    public void initialize() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);        
        
        btnPrint.setOpaque(false);
        btnPrint.setContentAreaFilled(false);
        btnPrint.setBorderPainted(false);

        buttonGroup1.setSelected(tipoRelatorioA.getModel(), true);

        ProcedureController procedureCon = new ProcedureController();
        Vector procedures = new Vector();
        this.procedures = procedureCon.onFindAll();
        procedures.addAll(this.procedures);
        selectProcedure.setModel(new DefaultComboBoxModel(procedures));
        selectProcedure.insertItemAt("", 0);
        selectProcedure.setSelectedIndex(0);

        title.setText("Relatórios");

        setMasks();
    }

    public void setMasks() {
        try {
            MaskFormatter maskCpf = new MaskFormatter("##/##/####");
            maskCpf.install(fieldDate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao aplicar máscara nos campos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fieldDate = new javax.swing.JFormattedTextField();
        title = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        selectProcedure = new javax.swing.JComboBox<>();
        fieldPrice = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        tipoRelatorioA = new javax.swing.JRadioButton();
        tipoRelatorioC = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDateActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        title.setText("Relatórios - Médico");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        btnSearch.setText("Filtrar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        selectProcedure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectProcedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProcedureActionPerformed(evt);
            }
        });

        fieldPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        fieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPriceActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20/04/2022", "Limpeza de Pele", "R$ 69,90"},
                {"06/04/2022", "Sombracelha", "R$ 45,00"}
            },
            new String [] {
                "Data", "Procedimento", "Valor"
            }
        ));
        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        btnPrint.setBorder(null);
        btnPrint.setBorderPainted(false);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipoRelatorioA);
        tipoRelatorioA.setText("Avaliações");
        tipoRelatorioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRelatorioAActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipoRelatorioC);
        tipoRelatorioC.setText("Consultas");
        tipoRelatorioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRelatorioCActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nesta data:");

        jLabel2.setText("Este procedimento:");

        jLabel3.setText("A partir deste valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoRelatorioA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoRelatorioC)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 120, Short.MAX_VALUE))
                            .addComponent(selectProcedure, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrint)
                    .addComponent(title))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoRelatorioA)
                    .addComponent(tipoRelatorioC))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateActionPerformed

    private void selectProcedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProcedureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectProcedureActionPerformed

    private void fieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPriceActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        if (table.getRowCount() < 1) {
            return;
        }

        int response = JOptionPane.showConfirmDialog(null,
                "Baixar o relatório dessa listagem?",
                "Relatório de listagem completa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            Attendance attendance = new Attendance();
            try {
                attendance.generateTablePDF("relatorio.pdf", "Relatório de Agendamentos", table);
                JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!");
            } catch (ReportsException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tipoRelatorioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRelatorioCActionPerformed
        // TODO add your handling code here:

        if (tipoRelatorioC.isSelected()) {
            fieldPrice.setEnabled(true);
            String dateStart;
            String dateEnd;
            List<String> date = new ArrayList();
            String dateField = fieldDate.getText().replaceAll(" ", "");
            String day;
            String month;
            String year;
            if (dateField.length() == 10) {
                day = dateField.substring(0, 2);
                month = dateField.substring(3, 5);
                year = dateField.substring(6, 10);
                dateStart = year + "/" + month + "/" + day + " 00:00:00";
                dateEnd = year + "/" + month + "/" + (Integer.parseInt(day) + 1) + " 00:00:00";
                date.add(dateStart);
                date.add(dateEnd);
            } else {
                date = null;
            }

            double price = 0.0;
            String priceField = fieldPrice.getText()
                    .replaceAll(" ", "")
                    .replaceAll("R", "")
                    .replaceAll("\\$", "");
            if (!priceField.equals("")) {
                price = Double.parseDouble(priceField.replaceAll("\\.", "").replaceAll(",", "\\."));
            }

            attendanceCon.onFindAllFilter(table, user.getPeople().getCPF(), "Consulta", date, selectProcedure.getSelectedItem().toString(), price);
            if (table.getRowCount() < 1) {
                btnPrint.setEnabled(false);
            } else {
                btnPrint.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tipoRelatorioCActionPerformed

    private void tipoRelatorioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRelatorioAActionPerformed
        // TODO add your handling code here:
        if (tipoRelatorioA.isSelected()) {
            fieldPrice.setEnabled(false);
            String dateStart;
            String dateEnd;
            List<String> date = new ArrayList();
            String dateField = fieldDate.getText().replaceAll(" ", "");
            String day;
            String month;
            String year;
            if (dateField.length() == 10) {
                day = dateField.substring(0, 2);
                month = dateField.substring(3, 5);
                year = dateField.substring(6, 10);
                dateStart = year + "/" + month + "/" + day + " 00:00:00";
                dateEnd = year + "/" + month + "/" + (Integer.parseInt(day) + 1) + " 00:00:00";
                date.add(dateStart);
                date.add(dateEnd);
            } else {
                date = null;
            }
            double price = 0.0;
            fieldPrice.setText("R$ ");

            attendanceCon.onFindAllFilter(table, user.getPeople().getCPF(), "Avaliacao", date, selectProcedure.getSelectedItem().toString(), price);
            if (table.getRowCount() < 1) {
                btnPrint.setEnabled(false);
            } else {
                btnPrint.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tipoRelatorioAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.previusScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String type;
        if (tipoRelatorioA.isSelected()) {
            type = "Avaliacao";
        } else {
            type = "Consulta";
        }

        String dateStart;
        String dateEnd;
        List<String> date = new ArrayList();
        String dateField = fieldDate.getText().replaceAll(" ", "");
        String day;
        String month;
        String year;
        if (dateField.length() == 10) {
            day = dateField.substring(0, 2);
            month = dateField.substring(3, 5);
            year = dateField.substring(6, 10);
            dateStart = year + "/" + month + "/" + day + " 00:00:00";
            dateEnd = year + "/" + month + "/" + (Integer.parseInt(day) + 1) + " 00:00:00";
            date.add(dateStart);
            date.add(dateEnd);
        } else {
            date = null;
        }

        double price = 0.0;
        String priceField = fieldPrice.getText()
                .replaceAll(" ", "")
                .replaceAll("R", "")
                .replaceAll("\\$", "");
        if (!priceField.equals("")) {
            price = Double.parseDouble(priceField.replaceAll("\\.", "").replaceAll(",", "\\."));
        }
        System.out.println("pr: " + price + "\nfil: " + priceField);

        attendanceCon.onFindAllFilter(table, user.getPeople().getCPF(), type, date, selectProcedure.getSelectedItem().toString(), price);
        if (table.getRowCount() < 1) {
            btnPrint.setEnabled(false);
        } else {
            btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void buttonGroup1ActionPerformed(java.awt.event.ActionEvent evt) {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField fieldDate;
    private javax.swing.JFormattedTextField fieldPrice;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectProcedure;
    private javax.swing.JTable table;
    private javax.swing.JRadioButton tipoRelatorioA;
    private javax.swing.JRadioButton tipoRelatorioC;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
