/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gp2.clinica_estetica.view;

import com.gp2.clinica_estetica.controller.UserController;
import com.gp2.clinica_estetica.model.People;
import com.gp2.clinica_estetica.model.exceptions.UserException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class FrResetPassword extends javax.swing.JFrame {
    private People currentPeople;

    /**
     * Creates new form FrSenha
     */
    public FrResetPassword() {
        initComponents();
    }
    
    public FrResetPassword(People currentUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.currentPeople = currentUser;
        
        boxNewPassword.setVisible(false);
        textSecurityQuestion.setText(currentUser.getUser().getSecurityQuestion());
    }
    
    public void setFieldsEnabled(Boolean flag) {
        textPassword.setEnabled(flag);
        textConfirmationPassword.setEnabled(flag);
        btnNewPassword.setEnabled(flag);
    }

    public void clearFields() {
        textPassword.setText("");
        textConfirmationPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxAnswerQuestion = new javax.swing.JPanel();
        btnVerifyAnswer = new javax.swing.JButton();
        textSecurityQuestion = new javax.swing.JLabel();
        textSecurityAnswer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        boxNewPassword = new javax.swing.JPanel();
        btnNewPassword = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        passwordLabel1 = new javax.swing.JLabel();
        textConfirmationPassword = new javax.swing.JPasswordField();
        btnBack2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVerifyAnswer.setText("Validar");
        btnVerifyAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyAnswerActionPerformed(evt);
            }
        });

        textSecurityQuestion.setText("Pergunta de segurança");

        textSecurityAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSecurityAnswerActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Responda à sua pergunta de pergunta de segurança para continuar");

        btnBack3.setText("Voltar");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxAnswerQuestionLayout = new javax.swing.GroupLayout(boxAnswerQuestion);
        boxAnswerQuestion.setLayout(boxAnswerQuestionLayout);
        boxAnswerQuestionLayout.setHorizontalGroup(
            boxAnswerQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxAnswerQuestionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boxAnswerQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSecurityQuestion)
                    .addComponent(textSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxAnswerQuestionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(boxAnswerQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxAnswerQuestionLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(boxAnswerQuestionLayout.createSequentialGroup()
                        .addComponent(btnBack3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerifyAnswer)
                        .addGap(46, 46, 46))))
        );
        boxAnswerQuestionLayout.setVerticalGroup(
            boxAnswerQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxAnswerQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(39, 39, 39)
                .addComponent(textSecurityQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(boxAnswerQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack3)
                    .addComponent(btnVerifyAnswer))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnNewPassword.setText("Atualizar senha");
        btnNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPasswordActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Insira sua nova senha");

        passwordLabel.setText("Senha");

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });

        passwordLabel1.setText("Confirmar senha");

        textConfirmationPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConfirmationPasswordActionPerformed(evt);
            }
        });

        btnBack2.setText("Voltar");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxNewPasswordLayout = new javax.swing.GroupLayout(boxNewPassword);
        boxNewPassword.setLayout(boxNewPasswordLayout);
        boxNewPasswordLayout.setHorizontalGroup(
            boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxNewPasswordLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(boxNewPasswordLayout.createSequentialGroup()
                        .addComponent(passwordLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textConfirmationPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boxNewPasswordLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPassword)))
                .addGap(71, 71, 71))
            .addGroup(boxNewPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxNewPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewPassword)
                .addGap(39, 39, 39))
        );
        boxNewPasswordLayout.setVerticalGroup(
            boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxNewPasswordLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(52, 52, 52)
                .addGroup(boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textConfirmationPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(boxNewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewPassword)
                    .addComponent(btnBack2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxAnswerQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(boxAnswerQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSecurityAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSecurityAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSecurityAnswerActionPerformed

    private void btnVerifyAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyAnswerActionPerformed
        // TODO add your handling code here:
        UserController userCon = new UserController();
        try {
            userCon.onCheckSecurityAnswer(this.currentPeople.getUser().getSecurityAnswer(), textSecurityAnswer.getText());
            boxAnswerQuestion.setVisible(false);
            boxNewPassword.setVisible(true);
        }  catch (UserException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerifyAnswerActionPerformed

    private void btnNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPasswordActionPerformed
        // TODO add your handling code here:
        
        if (textPassword.getText().length() > 7 && !textConfirmationPassword.getText().equals(textPassword.getText())) {
            JOptionPane.showMessageDialog(this, "Erro - Os campos 'senha' e 'confirmar senha' não conferem!");
            return;
        }
        
        try {
            UserController userCon = new UserController();
            userCon.onResetPassword(this.currentPeople.getCPF(), textPassword.getText().toLowerCase());
            
            this.setFieldsEnabled(false);
            int response = JOptionPane.showConfirmDialog(null,
                    "Ir para a tela de login?",
                    "Senha atualizada com sucesso!",
                    JOptionPane.OK_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                this.clearFields();
                FrLogin loginScreen = new FrLogin();
                this.setVisible(false);
                loginScreen.setVisible(true);
            }
        } catch (UserException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNewPasswordActionPerformed

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    private void textConfirmationPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConfirmationPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConfirmationPasswordActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        FrLogin loginScreen = new FrLogin();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        FrLogin loginScreen = new FrLogin();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_btnBack3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxAnswerQuestion;
    private javax.swing.JPanel boxNewPassword;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnNewPassword;
    private javax.swing.JButton btnVerifyAnswer;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JPasswordField textConfirmationPassword;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textSecurityAnswer;
    private javax.swing.JLabel textSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
